counting KNN stats added
error in calcDiffByArray:
 File "stats.py", line 368, in <module>
    countKNNStats()
  File "stats.py", line 355, in countKNNStats
    mse = calcDiffByArray(contours, "E:/studia/Informatyka/semestr VI/Informatyka w Medycynie/funduscopy/test_img/im"+x+'.ppm')
  File "stats.py", line 255, in calcDiffByArray
    return mean_squared_error(INPUT, RESULT)
  File "C:\Users\Ada\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sklearn\metrics\regression.py", line 238, in mean_squared_error
    y_true, y_pred, multioutput)
  File "C:\Users\Ada\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sklearn\metrics\regression.py", line 75, in _check_reg_targets
    check_consistent_length(y_true, y_pred)
  File "C:\Users\Ada\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sklearn\utils\validation.py", line 204, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [423500, 100]